Repository stellar/java-stellar-anchor-sdk, pull requests merged in 2022-06, with the labels that each got.

#295 bugfix: add NoArgsConstructor to RateFeeDetail so it can be parsed by kafka
  api-schema/src/main/java/org/stellar/anchor/api/sep/sep38/RateFeeDetail.java
Labels: bug, anchor platform mvp

#300 docs: bring documentation from the stellar/stellar-anchor-platform repository
  docs/Anchor Integration/Callbacks API.yml
  docs/Anchor Integration/Events Schema.yml
  docs/Anchor Integration/Platform API.yml
  docs/Anchor Integration/Readme.md
  docs/SEP-31/sep31-happypath.txt
Labels: documentation

#315 tests: fix end-to-end-tests
  end-to-end-tests/end_to_end_tests.py
Labels: bug, test server

#317 tests: re-enable SEP-38 validation tests using `@stellar/anchor-tests`
  .github/workflows/build_and_test.yml
  platform/src/test/resources/stellar-anchor-tests-sep-config.json
Labels: test server

#305 docs: refactor the project documentation
  README.md
  docs/00 - Stellar Anchor Platform.md
  docs/01 - Running & Configuring the Application/A - Running & Configuring the Application.md
  docs/01 - Running & Configuring the Application/B - Circle Payment Observer.md
  docs/01 - Running & Configuring the Application/README.md
  docs/02 - Contributing/A - CONTRIBUTING.md
  docs/02 - Contributing/B - Developer Tools.md
  docs/02 - Contributing/C - Logging Guidelines.md
  docs/02 - Contributing/D - Database Migration.md
  docs/02 - Contributing/E - Publishing the SDK.md
  docs/02 - Contributing/README.md
  docs/03 - Implementing the Anchor Server/Callbacks API.yml
  docs/03 - Implementing the Anchor Server/Events Schema.yml
  docs/03 - Implementing the Anchor Server/Platform API.yml
  docs/03 - Implementing the Anchor Server/Readme.md
  docs/03 - Implementing the Anchor Server/SEP-31/sep31-happypath.txt
  docs/04 - Subprojects Usage/A - payment-circle.md
  docs/CONTRIBUTING.md
  docs/anchor-platform.md
  docs/core.md
  docs/database-migration.md
  docs/developer-tools.md
  docs/git-and-coding-style.md
  docs/payment-services.md
  docs/publishing.md
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/anchor-config.yaml
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/readme.md
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/reference-server-config-map.yaml
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/reference-server-deployment.yaml
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/reference-server-ingress.yaml
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/reference-server-service.yaml
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/sep-server-config-map.yaml
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/sep-server-deployment.yaml
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/sep-server-ingress.yaml
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/sep-server-service.yaml
  docs/resources/deployment-examples/example-k8s/anchor-platform-dev/zookeeper-kafka-deployment.yaml
  docs/resources/docker-examples/kafka/docker-compose.yaml
  docs/resources/img/anchor-platform-components-architecture.jpeg
  docs/resources/img/configure-intellij-gradle.png
  docs/resources/img/gradle-reload-all.png
  docs/resources/img/liquibase-changelog1.png
  docs/resources/img/liquibase-changelog2.png
  docs/resources/img/liquibase-changelog3.png
  docs/resources/img/liquibase-db-connection.png
  docs/resources/img/no-giphy.gif
  docs/resources/img/running-the-tests.png
  platform/src/main/java/org/stellar/anchor/platform/AnchorPlatformServer.java
  platform/src/main/java/org/stellar/anchor/platform/configurator/PropertiesReader.java
  platform/src/main/resources/example.env
  platform/src/test/kotlin/org/stellar/anchor/platform/configurator/ConfiguratorTest.kt
  service-runner/src/main/java/org/stellar/anchor/platform/ServiceRunner.java
Labels: documentation

#330 hotfix: fix `gson` reference cycle triggered by a print
  integration-tests/src/main/kotlin/org/stellar/anchor/platform/Sep12Client.kt
  integration-tests/src/test/kotlin/org/stellar/anchor/platform/PlatformTests.kt
  platform/src/main/java/org/stellar/anchor/platform/controller/Sep12Controller.java
Labels: bug

#334 docs: document the step-by-step of how partners should implement their anchor servers
  docs/00 - Stellar Anchor Platform.md
  docs/01 - Running & Configuring the Application/A - Running & Configuring the Application.md
  docs/03 - Implementing the Anchor Server/Communication/Callbacks API.yml
  docs/03 - Implementing the Anchor Server/Communication/Events Schema.yml
  docs/03 - Implementing the Anchor Server/Communication/Platform API.yml
  docs/03 - Implementing the Anchor Server/README.md
  docs/03 - Implementing the Anchor Server/Readme.md
  docs/03 - Implementing the Anchor Server/SEP-31/sep31-happypath.txt
  docs/04 - Subprojects Usage/A - Circle Payment Service.md
  docs/README.md
  platform/src/main/java/org/stellar/anchor/platform/AnchorPlatformServer.java
  platform/src/main/java/org/stellar/anchor/platform/EventsConfig.java
Labels: documentation, anchor platform mvp

#352 bugfix: remove duplicate USDC asset that was causing USDC transfer to not work
  end-to-end-tests/end_to_end_tests.py
  integration-tests/src/test/kotlin/org/stellar/anchor/platform/AnchorPlatformIntegrationTest.kt
  integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep31Tests.kt
  integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep38Tests.kt
  platform/src/main/resources/assets-test.json
  platform/src/main/resources/sep1/stellar-wks.toml
Labels: bug

#347 core: Fix SEP-10 multi-signature authentication.
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/RateService.java
  integration-tests/src/main/kotlin/org/stellar/anchor/platform/Sep10Client.kt
  integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep10Tests.kt
  integration-tests/src/test/kotlin/org/stellar/anchor/platform/SepTestSuite.kt
  platform/src/main/java/org/stellar/anchor/platform/condition/AbstractOnSepsEnabled.java
  platform/src/main/java/org/stellar/anchor/platform/condition/ConditionalOnAllSepsEnabled.java
  platform/src/main/java/org/stellar/anchor/platform/condition/OnAllSepEnabledCondition.java
  platform/src/main/java/org/stellar/anchor/platform/condition/OnAnySepEnabledCondition.java
  platform/src/main/java/org/stellar/anchor/platform/controller/Sep10Controller.java
  platform/src/main/java/org/stellar/anchor/platform/controller/Sep12Controller.java
  platform/src/main/java/org/stellar/anchor/platform/controller/Sep1Controller.java
  platform/src/main/java/org/stellar/anchor/platform/controller/Sep24Controller.java
  platform/src/main/java/org/stellar/anchor/platform/controller/Sep31Controller.java
  platform/src/main/java/org/stellar/anchor/platform/controller/Sep38Controller.java
Labels: bug, SEP-10

#354 git: add pre-commit hook that guarantees the code is formatted
  build.gradle.kts
  scripts/pre-commit.sh
Labels: enhancement

#357 sep10: fix sep10 challenge transaction validation crash when signed with Lobstr VAULT
  core/build.gradle.kts
  core/src/main/java/org/stellar/anchor/asset/AssetService.java
  core/src/main/java/org/stellar/anchor/asset/JsonAssetService.java
  core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
  core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
  core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
  core/src/test/resources/test_account_with_noncompliant_signer.json
  integration-tests/src/test/kotlin/org/stellar/anchor/platform/PlatformTests.kt
  integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep31Tests.kt
  settings.gradle.kts
Labels: bug
