Repository stellar/java-stellar-anchor-sdk, pull requests merged in 2022-07, with the labels that each got.

#383 docs: add high-level database sizing information
  docs/00 - Stellar Anchor Platform.md
Labels: documentation

#386 bugfix: fix auth header when the authorization type is NONE
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/client/PlatformApiClient.java
  core/src/main/java/org/stellar/anchor/auth/AuthHelper.java
  core/src/test/kotlin/org/stellar/anchor/auth/AuthHelperTest.kt
  core/src/test/kotlin/org/stellar/anchor/auth/JwtServiceTest.kt
  platform/src/main/java/org/stellar/anchor/platform/callback/PlatformIntegrationHelper.java
  platform/src/test/kotlin/org/stellar/anchor/platform/callback/PlatformIntegrationHelperTest.kt
Labels: bug

#421 Polishes
  .github/workflows/build_and_test.yml
  api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Field.java
  api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/ProvidedField.java
  api-schema/src/main/java/org/stellar/anchor/api/sep/sep12/Sep12PutCustomerRequest.java
  core/src/main/java/org/stellar/anchor/filter/ApiKeyFilter.java
  core/src/main/java/org/stellar/anchor/filter/JwtTokenFilter.java
  core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt
  platform/src/main/java/org/stellar/anchor/platform/config/PropertyAppConfig.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertyCircleConfig.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertySep1Config.java
  platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
  platform/src/main/resources/log4j2.yaml
  platform/src/test/kotlin/org/stellar/anchor/platform/LogAppenderTest.kt
  platform/src/test/kotlin/org/stellar/anchor/platform/config/AppConfigTest.kt
  platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep31ConfigTest.kt
Labels: enhancement

#436 improvement: add extra logs
  core/src/main/java/org/stellar/anchor/filter/ApiKeyFilter.java
  core/src/main/java/org/stellar/anchor/filter/JwtTokenFilter.java
  core/src/main/java/org/stellar/anchor/util/UrlValidationUtil.java
  platform/src/main/java/org/stellar/anchor/platform/ConfigManagementConfig.java
  platform/src/main/java/org/stellar/anchor/platform/callback/PlatformIntegrationHelper.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertyAppConfig.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertyCircleConfig.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertyCirclePaymentObserverConfig.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertyEventConfig.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertySep10Config.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertySep12Config.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertySep38Config.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertySqsConfig.java
  platform/src/test/kotlin/org/stellar/anchor/platform/config/EventConfigTest.kt
  platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep12ConfigTest.kt
  platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep1ConfigTest.kt
  platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep31ConfigTest.kt
  platform/src/test/kotlin/org/stellar/anchor/platform/config/Sep38ConfigTest.kt
Labels: enhancement

#430 all: Issue 416 Implement GET `/unique_address` of the callback API
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/config/AppSettings.java
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/UniqueAddressController.java
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/UniqueAddressService.java
  anchor-reference-server/src/main/resources/anchor-reference-server.yaml
  api-schema/src/main/java/org/stellar/anchor/api/callback/GetUniqueAddressResponse.java
  api-schema/src/main/java/org/stellar/anchor/api/callback/UniqueAddressIntegration.java
  core/build.gradle.kts
  core/src/main/java/org/stellar/anchor/config/Sep31Config.java
  core/src/main/java/org/stellar/anchor/sep31/Sep31DepositInfoGenerator.java
  core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
  core/src/test/kotlin/org/stellar/anchor/TestHelper.kt
  core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
  docs/03 - Implementing the Anchor Server/Communication/Callbacks API.yml
  platform/src/main/java/org/stellar/anchor/platform/IntegrationConfig.java
  platform/src/main/java/org/stellar/anchor/platform/SepConfig.java
  platform/src/main/java/org/stellar/anchor/platform/callback/RestUniqueAddressIntegration.java
  platform/src/main/java/org/stellar/anchor/platform/config/PropertySep31Config.java
  platform/src/main/java/org/stellar/anchor/platform/service/Sep31DepositInfoGeneratorApi.java
  platform/src/main/java/org/stellar/anchor/platform/service/Sep31DepositInfoGeneratorCircle.java
  platform/src/main/java/org/stellar/anchor/platform/service/Sep31DepositInfoGeneratorSelf.java
  platform/src/main/resources/anchor-config-defaults.yaml
  platform/src/test/kotlin/org/stellar/anchor/platform/service/Sep31DepositInfoGeneratorApiTest.kt
  platform/src/test/kotlin/org/stellar/anchor/sep31/Sep31DepositInfoGeneratorTest.kt
Labels: anchor platform mvp, SEP-31

#444 hotfix: solve issue where `uniqueAddressService` was crashing
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/UniqueAddressController.java
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/UniqueAddressService.java
  core/src/main/java/org/stellar/anchor/util/ConditionalOnPropertyNotEmpty.java
Labels: bug

#440 enhancement & fixes: update the code in preparation for handling SEP-31 non-happy-paths caused by `PENDING_CUSTOMER_INFO_UPDATE`
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/RateController.java
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/model/StellarIdConverter.java
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/service/CustomerService.java
  api-schema/src/main/java/org/stellar/anchor/api/exception/Sep31CustomerInfoNeededException.java
  api-schema/src/main/java/org/stellar/anchor/api/exception/Sep31MissingFieldException.java
  api-schema/src/main/java/org/stellar/anchor/api/platform/GetTransactionResponse.java
  api-schema/src/main/java/org/stellar/anchor/api/platform/PatchTransactionRequest.java
  api-schema/src/main/java/org/stellar/anchor/api/platform/Refunds.java
  api-schema/src/main/java/org/stellar/anchor/api/sep/AssetInfo.java
  api-schema/src/main/java/org/stellar/anchor/api/sep/SepTransactionStatus.java
  api-schema/src/main/java/org/stellar/anchor/api/sep/sep31/Sep31GetTransactionResponse.java
  api-schema/src/main/java/org/stellar/anchor/api/shared/Customers.java
  api-schema/src/main/java/org/stellar/anchor/api/shared/Refund.java
  api-schema/src/main/java/org/stellar/anchor/api/shared/RefundPayment.java
  api-schema/src/main/java/org/stellar/anchor/api/shared/StellarId.java
  core/src/main/java/org/stellar/anchor/event/models/QuoteEvent.java
  core/src/main/java/org/stellar/anchor/event/models/TransactionEvent.java
  core/src/main/java/org/stellar/anchor/sep31/RefundPayment.java
  core/src/main/java/org/stellar/anchor/sep31/RefundPaymentBuilder.java
  core/src/main/java/org/stellar/anchor/sep31/Refunds.java
  core/src/main/java/org/stellar/anchor/sep31/RefundsBuilder.java
  core/src/main/java/org/stellar/anchor/sep31/Sep31Service.java
  core/src/main/java/org/stellar/anchor/sep31/Sep31Transaction.java
  core/src/main/java/org/stellar/anchor/sep31/Sep31TransactionBuilder.java
  core/src/main/java/org/stellar/anchor/sep31/Sep31TransactionStore.java
  core/src/main/java/org/stellar/anchor/sep38/Sep38QuoteStore.java
  core/src/main/java/org/stellar/anchor/sep38/Sep38Service.java
  core/src/main/java/org/stellar/anchor/util/SepHelper.java
  core/src/test/java/org/stellar/anchor/sep31/PojoSep31RefundPayment.java
  core/src/test/java/org/stellar/anchor/sep31/PojoSep31Refunds.java
  core/src/test/java/org/stellar/anchor/sep31/PojoSep31Transaction.java
  core/src/test/kotlin/org/stellar/anchor/sep31/Sep31HelperTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
  docs/00 - Stellar Anchor Platform.md
  docs/03 - Implementing the Anchor Server/Communication/Platform API.yml
  integration-tests/src/test/kotlin/org/stellar/anchor/platform/Sep12Tests.kt
  platform/src/main/java/org/stellar/anchor/platform/controller/Sep31Controller.java
  platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31RefundPayment.java
  platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Refunds.java
  platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Transaction.java
  platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31TransactionStore.java
  platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
  platform/src/main/java/org/stellar/anchor/platform/service/TransactionService.java
  platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt
  platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
  platform/src/test/resources/stellar-anchor-tests-sep-config.json
Labels: bug, enhancement
