Repository stellar/java-stellar-anchor-sdk, pull requests merged in 2022-08, with the labels that each got.

#453 platform: Fix error when not running LogAppenderTest from console
  platform/src/test/kotlin/org/stellar/anchor/platform/LogAppenderTest.kt
Labels: bug

#456 helm: issue-455: Add uniqueAddressIntegrationEndPoint to helm chart
  docs/resources/deployment-examples/example-fargate/example_config/anchor_config.yaml
  helm-charts/sep-service/example_values.yaml
  helm-charts/sep-service/templates/configmap.yaml
  integration-tests/src/test/resources/integration-test.anchor-config.yaml
  platform/src/main/resources/anchor-docker-compose-config.yaml
Labels: bug

#475 bugfix: fix issue where the incoming payment was not populating the event correctly
  end-to-end-tests/end_to_end_tests.py
  platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Transaction.java
  platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
  platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt
Labels: bug

#505 hotfix: fix build.gradle.kts from the integration-tests package, so the integration tests can be executed
  integration-tests/build.gradle.kts
Labels: bug

#510 hotfix: SEP-12's deletion should not require the memo to be in the JWT_TOKEN when it is sent on the request body
  core/src/main/java/org/stellar/anchor/sep12/Sep12Service.java
  core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt
Labels: bug

#507 core: Use Kotlin backticks to rename tests to descriptive names
  api-schema/src/main/java/org/stellar/anchor/api/sep/sep10/ChallengeRequest.java
  core/src/test/kotlin/org/stellar/anchor/api/sep/sep10/ChallengeRequestTest.kt
  core/src/test/kotlin/org/stellar/anchor/api/sep/sep10/ChallengeResponseTest.kt
  core/src/test/kotlin/org/stellar/anchor/api/sep/sep10/ValidationRequestTest.kt
  core/src/test/kotlin/org/stellar/anchor/api/sep/sep10/ValidationResponseTest.kt
  core/src/test/kotlin/org/stellar/anchor/api/sep/sep24/Sep24DtoTests.kt
  core/src/test/kotlin/org/stellar/anchor/asset/ResourceJsonAssetServiceTest.kt
  core/src/test/kotlin/org/stellar/anchor/auth/AuthHelperTest.kt
  core/src/test/kotlin/org/stellar/anchor/auth/JwtServiceTest.kt
  core/src/test/kotlin/org/stellar/anchor/auth/JwtTokenTest.kt
  core/src/test/kotlin/org/stellar/anchor/dto/SepExceptionResponseTest.kt
  core/src/test/kotlin/org/stellar/anchor/dto/sep31/Sep31PostTransactionRequestTest.kt
  core/src/test/kotlin/org/stellar/anchor/dto/sep38/InfoResponseTest.kt
  core/src/test/kotlin/org/stellar/anchor/filter/ApiKeyFilterTest.kt
  core/src/test/kotlin/org/stellar/anchor/filter/JwtTokenFilterTest.kt
  core/src/test/kotlin/org/stellar/anchor/filter/NoneFilterTest.kt
  core/src/test/kotlin/org/stellar/anchor/horizon/HorizonTest.kt
  core/src/test/kotlin/org/stellar/anchor/model/Sep24TransactionTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep1/Sep1ServiceTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep10/Sep10ServiceTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep12/Sep12ServiceTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep24/Sep24ServiceTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep31/RefundPaymentTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep31/RefundsTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep31/Sep31HelperTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep31/Sep31ServiceTest.kt
  core/src/test/kotlin/org/stellar/anchor/sep38/Sep38ServiceTest.kt
  core/src/test/kotlin/org/stellar/anchor/util/DateUtilTest.kt
  core/src/test/kotlin/org/stellar/anchor/util/FileUtilTest.kt
  core/src/test/kotlin/org/stellar/anchor/util/LogTest.kt
  core/src/test/kotlin/org/stellar/anchor/util/MathHelperTest.kt
  core/src/test/kotlin/org/stellar/anchor/util/MemoHelperTest.kt
  core/src/test/kotlin/org/stellar/anchor/util/NetUtilTest.kt
  core/src/test/kotlin/org/stellar/anchor/util/OkHttpUtilTest.kt
  core/src/test/kotlin/org/stellar/anchor/util/PropertyUtilTest.java
  core/src/test/kotlin/org/stellar/anchor/util/PropertyUtilTest.kt
  core/src/test/kotlin/org/stellar/anchor/util/SepHelperTest.kt
  core/src/test/kotlin/org/stellar/anchor/util/SepLanguageHelperTest.kt
  integration-tests/src/test/kotlin/org/stellar/anchor/platform/PlatformTests.kt
  platform/src/main/java/org/stellar/anchor/platform/controller/Sep10Controller.java
  platform/src/main/java/org/stellar/anchor/platform/service/MetricEmitterService.java
Labels: enhancement

#512 platform: Fix the contention problem that causes locked database.
  platform/src/main/java/org/stellar/anchor/platform/service/MetricEmitterService.java
Labels: bug

#513 hotfix: CI was not being executed in the develop branch after merging
  .github/workflows/build_and_test.yml
Labels: bug, gitflow

#511 Feature: release checklist
  .github/ISSUE_TEMPLATE/release_a_new_version.md
  CHANGELOG.md
  settings.gradle.kts
Labels: gitflow

#517 Feature: when no cursor can be found in the database, the Stellar streamer will start from the most recent cursor in the Network
  platform/src/main/java/org/stellar/anchor/platform/payment/observer/stellar/StellarPaymentObserver.java
  platform/src/test/kotlin/org/stellar/anchor/platform/payment/observer/stellar/StellarPaymentObserverTest.kt
Labels: enhancement

#514 Move @Bean declarations from AnchorPlatformServer to HelperConfig and…
  platform/src/main/java/org/stellar/anchor/platform/AnchorPlatformServer.java
  platform/src/main/java/org/stellar/anchor/platform/HelperConfig.java
  platform/src/main/java/org/stellar/anchor/platform/MetricsConfig.java
Labels: enhancement

#519 Feature: log requests and responses
  platform/src/main/java/org/stellar/anchor/platform/RequestLoggerConfig.java
  platform/src/main/java/org/stellar/anchor/platform/utils/RequestLoggerFilter.java
  platform/src/main/java/org/stellar/anchor/platform/utils/RequestResponseMessage.java
Labels: enhancement

#515 Feature: add versioning to the project, subprojects and to the /health endpoint
  api-schema/build.gradle.kts
  api-schema/src/main/java/org/stellar/anchor/api/platform/HealthCheckResponse.java
  api-schema/src/main/java/org/stellar/anchor/api/shared/Metadata.java
  api-schema/src/main/resources/metadata.properties
  api-schema/src/test/kotlin/org/stellar/anchor/api/shared/MetadataTest.kt
  api-schema/src/test/resources/metadata.properties
  build.gradle.kts
  core/build.gradle.kts
  service-runner/build.gradle.kts
Labels: gitflow

#522 hotfix: add missing DB migration and remove unused data models
  platform/src/main/java/org/stellar/anchor/platform/data/Customer.java
  platform/src/main/java/org/stellar/anchor/platform/data/CustomerStatus.java
  platform/src/main/resources/db/migration/V4__add_observer_tables_and_drop_sep31_transaction_message_column.sql
Labels: bug

#526 hotfix: add missing AWS IAM dependency
  build.gradle.kts
  platform/build.gradle.kts
Labels: bug

#527 risk: Fix high-risk vulnerabilities reported by Snyk
  anchor-reference-server/src/main/java/org/stellar/anchor/reference/controller/Sep24InteractiveController.java
  core/src/main/java/org/stellar/anchor/auth/JwtService.java
  platform/src/main/java/org/stellar/anchor/platform/controller/CirclePaymentObserverController.java
  platform/src/main/java/org/stellar/anchor/platform/payment/observer/circle/CirclePaymentObserverService.java
  platform/src/test/kotlin/org/stellar/anchor/platform/payment/observer/CirclePaymentObserverServiceTest.kt
Labels: risk

#534 Feature: add default issue templates for bug reports, feature requests and some useful links
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: enhancement

#533 Feature: configure CI for the Gitflow release process
  .github/workflows/basic_tests.yml
  .github/workflows/release.yml
  .github/workflows/release_develop.yml
  .github/workflows/release_release.yml
  build.gradle.kts
  core/build.gradle.kts
Labels: gitflow, cd-ci

#539 Fix: some CI jobs were running twice
  .github/workflows/basic_tests.yml
  .github/workflows/release_main.yml
  Makefile
Labels: bug, gitflow, cd-ci

#529 Feature: update how the platform deals with incoming payments with insufficient amounts
  api-schema/src/main/java/org/stellar/anchor/api/platform/GetTransactionResponse.java
  api-schema/src/main/java/org/stellar/anchor/api/shared/StellarPayment.java
  api-schema/src/main/java/org/stellar/anchor/api/shared/StellarTransaction.java
  api-schema/src/test/kotlin/org/stellar/anchor/api/shared/StellarPaymentTest.kt
  api-schema/src/test/kotlin/org/stellar/anchor/api/shared/StellarTransactionTest.kt
  core/src/main/java/org/stellar/anchor/event/models/Payment.java
  core/src/main/java/org/stellar/anchor/event/models/StellarTransaction.java
  core/src/main/java/org/stellar/anchor/event/models/TransactionEvent.java
  core/src/main/java/org/stellar/anchor/sep31/Sep31Transaction.java
  core/src/main/java/org/stellar/anchor/sep31/Sep31TransactionBuilder.java
  core/src/test/java/org/stellar/anchor/sep31/PojoSep31Transaction.java
  core/src/test/kotlin/org/stellar/anchor/sep31/Sep31TransactionTest.kt
  docs/03 - Implementing the Anchor Server/Communication/Platform API.yml
  gradle/libs.versions.toml
  platform/build.gradle.kts
  platform/src/main/java/org/stellar/anchor/platform/data/JdbcSep31Transaction.java
  platform/src/main/java/org/stellar/anchor/platform/data/StellarTransaction.java
  platform/src/main/java/org/stellar/anchor/platform/payment/observer/stellar/StellarPayment.java
  platform/src/main/java/org/stellar/anchor/platform/payment/observer/stellar/StellarTransaction.java
  platform/src/main/java/org/stellar/anchor/platform/service/PaymentOperationToEventListener.java
  platform/src/main/resources/db/migration/V5__sep31_transaction_now_store_stellar_transactions_as_json.sql
  platform/src/test/kotlin/org/stellar/anchor/platform/service/PaymentOperationToEventListenerTest.kt
  platform/src/test/kotlin/org/stellar/anchor/platform/service/TransactionServiceTest.kt
Labels: enhancement, SEP-31
